psql -d imdb -U ubuntu -p 5432 < ../../queries/job/10a.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/10b.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/10c.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/11a.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/11b.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/11c.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/11d.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/12a.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/12b.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/12c.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/13a.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/13b.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/13c.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/13d.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/14a.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/14b.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/14c.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/15a.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/15b.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/15c.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/15d.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/16a.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/16b.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/16c.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/16d.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/17a.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/17b.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/17c.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/17d.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/17e.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/17f.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/18a.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/18b.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/18c.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/19a.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/19b.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/19c.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/19d.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/1a.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/1b.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/1c.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/1d.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/20a.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/20b.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/20c.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/21a.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/21b.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/21c.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/22a.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/22b.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/22c.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/22d.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/23a.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/23b.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/23c.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/24a.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/24b.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/25a.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/25b.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/25c.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/26a.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/26b.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/26c.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/27a.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/27b.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/27c.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/28a.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/28b.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/28c.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/29a.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/29b.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/29c.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/2a.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/2b.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/2c.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/2d.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/30a.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/30b.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/30c.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/31a.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/31b.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/31c.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/32a.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/32b.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/33a.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/33b.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/33c.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/3a.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/3b.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/3c.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/4a.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/4b.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/4c.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/5a.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/5b.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/5c.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/6a.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/6b.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/6c.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/6d.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/6e.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/6f.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/7a.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/7b.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/7c.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/8a.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/8b.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/8c.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/8d.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/9a.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/9b.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/9c.sql
psql -d imdb -U ubuntu -p 5432 < ../../queries/job/9d.sql
